# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c360ee67c220a3feabab4e915489e36f91251d7f59eb822bad77b397599db3e96e06e1e36554c716d7af521add070d9a47837ff6aa6d86def988421de568126e

test:
  secret_key_base: 87b9ab7613131c729b0b370956e03c2634f7474621b3890710294c3807ad709febe75da2b6d8f33782d48250fd8196ff4d977ba36cc6eb4364335be1bdae59bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
